name = "droplets-api"
main = "workers/api/index.ts"
compatibility_date = "2024-08-30"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "droplets-api-production"

[[d1_databases]]
binding = "DB"
database_name = "droplets-db"
database_id = "ffdec4f8-a0ca-447c-8ad4-186eae2bf33e"

[[kv_namespaces]]
binding = "CACHE"
id = "aa1fb3b47d5a46b6802b6b2973f4cf28"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "droplets-media"

# Durable Objects (temporarily disabled for initial deployment)
# [[durable_objects.bindings]]
# name = "WORLD"
# class_name = "WorldRoom"
# script_name = "droplets-api"

[vars]
ENVIRONMENT = "development"
JWT_SECRET = "development-jwt-secret-key-change-in-production"
TURNSTILE_SECRET_KEY = "dummy-turnstile-key"