name = "droplets-api"
main = "workers/api/index.ts"
compatibility_date = "2024-08-30"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "droplets-api-production"

[[d1_databases]]
binding = "DB"
database_name = "droplets-db"
database_id = "YOUR_D1_DATABASE_ID_HERE"

[[kv_namespaces]]
binding = "CACHE"
id = "YOUR_KV_NAMESPACE_ID_HERE"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "droplets-media"

# Durable Objects (temporarily disabled for initial deployment)
# [[durable_objects.bindings]]
# name = "WORLD"
# class_name = "WorldRoom"
# script_name = "droplets-api"

[vars]
ENVIRONMENT = "development"